name: Publish to PyPI

on:
  release:
    types: [published]  # Runs ONLY when you click "Create Release" on GitHub

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi  # Matches what you typed in PyPI website
    permissions:
      id-token: write  # REQUIRED for Trusted Publishing

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build Package
        run: uv build

      - name: Publish to PyPI
        # This action uses the "Trusted" connection automatically
        uses: pypa/gh-action-pypi-publish@release/v1